version: '3.8'

services:
  backend:
    image: 'pccw-backend:latest'
    ports:
      - "8080:8080"
    build:
      context: ./backend
    container_name: pccw-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pccw
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=adminadmin

  db:
    image: 'postgres:14.8-alpine3.18'
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=pccw
  frontend:
    image: 'pccw-frontend:latest'
    ports:
      - "3000:3000"
    build:
      context: ./frontend
    container_name: pccw-frontend
    depends_on:
      - backend
    environment:
      - API_HOST=http://backend:8080