spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/pccw"
    username: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:changelog.xml"
  mail:
    host: smtp.ethereal.email
    port: 587
    username: jedidiah78@ethereal.email
    password: Ajugv4GnAfSUsg6xbY
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true